<a href="https://colab.research.google.com/github/NadimMahmud3219/NumPy-array-everything-you-need-know/blob/main/Everything_about_NumPy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. What is NumPy?

NumPy (Numerical Python) is a Python library used for:

Fast mathematical operations

Efficient storage of large datasets

Linear algebra, matrices, statistics

Foundation for libraries like Pandas, SciPy, Scikit-learn, TensorFlow, PyTorch

Its core feature is the ndarray (N-dimensional array).



2. NumPy Array (ndarray) Overview

A NumPy array is:

Homogeneous (all elements same data type)

Fixed-size

Fast (implemented in C)

Supports vectorization (operations on entire arrays without loops)

In [1]:
# first of all we need import it
import numpy as np

In [3]:
# this is one of the method how we can declare an array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [6]:
#two dimentional array
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
# we can use python in build function
np.zeros((2,2))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.full((2,3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [12]:
# define step
np.arange(0, 10, 2)   # (start, end, step)

array([0, 2, 4, 6, 8])

In [13]:
np.linspace(0, 1, 5)  # equal intervals

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# we can genarate random value
np.random.rand(3,3)

array([[0.01501914, 0.46976831, 0.95533128],
       [0.14089007, 0.36465971, 0.8452163 ],
       [0.09403248, 0.39560228, 0.86037052]])

In [15]:
np.random.randn(3,3)

array([[ 0.75708868,  0.98137913, -0.58691284],
       [ 0.47062366,  1.10264519,  0.47708854],
       [-0.26675374,  1.05209377, -0.30065391]])

In [16]:
np.random.randint(0, 10, 5) # random integer

array([5, 7, 7, 7, 0])

In [26]:
# detect dimention
arr_ex = np.random.randn(2,4)
arr_ex.ndim

2

In [27]:
arr_ex.dtype # check data type

dtype('float64')

In [28]:
# indexing
arr_ex

array([[-0.86806216,  0.2554581 , -0.11858391,  1.78162851],
       [-0.05205849, -1.63555372,  0.20222857,  0.10098697]])

In [29]:
arr_ex[0] # aceessing particular row

array([-0.86806216,  0.2554581 , -0.11858391,  1.78162851])

In [31]:
arr_ex[0,0] # accessing particular value

np.float64(-0.8680621637673929)

In [34]:
arr_ex[:,0] # accesing column

array([-0.86806216, -0.05205849])

In [36]:
# array operation
arr1 = np.array([[2,3],
                 [4,5]])
arr1

array([[2, 3],
       [4, 5]])

In [38]:
# array operation
arr2 = np.array([[5,6],
                 [7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [39]:
arr1+arr2

array([[ 7,  9],
       [11, 13]])

In [40]:
arr1-arr2

array([[-3, -3],
       [-3, -3]])

In [41]:
arr1/arr2

array([[0.4       , 0.5       ],
       [0.57142857, 0.625     ]])

In [42]:
arr1 ** arr2

array([[    32,    729],
       [ 16384, 390625]])

In [43]:
# using universal function
np.sqrt(arr1)

array([[1.41421356, 1.73205081],
       [2.        , 2.23606798]])

In [44]:
np.log(arr2)

array([[1.60943791, 1.79175947],
       [1.94591015, 2.07944154]])

In [45]:
np.sin(arr1)

array([[ 0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427]])

In [46]:
np.abs(arr1)

array([[2, 3],
       [4, 5]])

In [47]:
# broadcasting
a = np.array([1,2,3])
b = 2
print(a + b)   # [3,4,5]


[3 4 5]


In [48]:
# transpose
np.transpose(arr1)

array([[2, 4],
       [3, 5]])

In [49]:
# statistical operation
arr1.mean()

np.float64(3.5)

In [50]:
arr1.min()

np.int64(2)

In [51]:
arr1.max()

np.int64(5)

In [52]:
arr1.sum()

np.int64(14)

In [53]:
arr1.std()

np.float64(1.118033988749895)

In [54]:
arr1.var()

np.float64(1.25)

## sorting

In [62]:
arr3 = np.array([[10,6],
                 [8,3]])

In [63]:
np.sort(arr3)

array([[ 6, 10],
       [ 3,  8]])

###Python lists and NumPy arrays walk into a bar.
The bartender says:
“Sorry, we only serve vectorized operations here.”